<a href="https://colab.research.google.com/github/Sivanunna/Logicmojo-AI-ML-Sept25--siva-/blob/main/Random_forest.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Welcome to Colab!

In [110]:
import numpy as np
import pandas as pd
# Visualization
import matplotlib.pyplot as plt
import seaborn as sns

In [111]:
import warnings
warnings.filterwarnings('ignore')

In [112]:
from google.colab import drive
drive.mount('/content/drive')
df = pd.read_csv('/content/drive/MyDrive/WA_Fn-UseC_-Telco-Customer-Churn.csv')
df

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

,customerID,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,...,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn
0,7590-VHVEG,Female,0,Yes,No,1,No,No phone service,DSL,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,29.85,29.85,No
1,5575-GNVDE,Male,0,No,No,34,Yes,No,DSL,Yes,...,Yes,No,No,No,One year,No,Mailed check,56.95,1889.5,No
2,3668-QPYBK,Male,0,No,No,2,Yes,No,DSL,Yes,...,No,No,No,No,Month-to-month,Yes,Mailed check,53.85,108.15,Yes
3,7795-CFOCW,Male,0,No,No,45,No,No phone service,DSL,Yes,...,Yes,Yes,No,No,One year,No,Bank transfer (automatic),42.30,1840.75,No
4,9237-HQITU,Female,0,No,No,2,Yes,No,Fiber optic,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,70.70,151.65,Yes
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7038,6840-RESVB,Male,0,Yes,Yes,24,Yes,Yes,DSL,Yes,...,Yes,Yes,Yes,Yes,One year,Yes,Mailed check,84.80,1990.5,No
7039,2234-XADUH,Female,0,Yes,Yes,72,Yes,Yes,Fiber optic,No,...,Yes,No,Yes,Yes,One year,Yes,Credit card (automatic),103.20,7362.9,No
7040,4801-JZAZL,Female,0,Yes,Yes,11,No,No phone service,DSL,Yes,...,No,No,No,No,Month-to-month,Yes,Electronic check,29.60,346.45,No
7041,8361-LTMKD,Male,1,Yes,No,4,Yes,Yes,Fiber optic,No,...,No,No,No,No,Month-to-month,Yes,Mailed check,74.40,306.6,Yes
7042,3186-AJIEK,Male,0,No,No,66,Yes,No,Fiber optic,Yes,...,Yes,Yes,Yes,Yes,Two year,Yes,Bank transfer (automatic),105.65,6844.5,No

In [113]:
df.shape

(7043, 21)

In [114]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7043 entries, 0 to 7042
Data columns (total 21 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   customerID        7043 non-null   object
 1   gender            7043 non-null   object
 2   SeniorCitizen     7043 non-null   int64
 3   Partner           7043 non-null   object
 4   Dependents        7043 non-null   object
 5   tenure            7043 non-null   int64
 6   PhoneService      7043 non-null   object
 7   MultipleLines     7043 non-null   object
 8   InternetService   7043 non-null   object
 9   OnlineSecurity    7043 non-null   object
 10  OnlineBackup      7043 non-null   object
 11  DeviceProtection  7043 non-null   object
 12  TechSupport       7043 non-null   object
 13  StreamingTV       7043 non-null   object
 14  StreamingMovies   7043 non-null   object
 15  Contract          7043 non-null   object
 16  PaperlessBilling  7043 non-null   object
 17  PaymentMethod     7043 non-null   object
 18  MonthlyCharges    7043 non-null   float64
 19  TotalCharges      7043 non-null   object
 20  Churn             7043 non-null   object
dtypes: float64(1), int64(2), object(18)
memory usage: 1.1+ MB

In [115]:
df.isnull().sum()

customerID          0
gender              0
SeniorCitizen       0
Partner             0
Dependents          0
tenure              0
PhoneService        0
MultipleLines       0
InternetService     0
OnlineSecurity      0
OnlineBackup        0
DeviceProtection    0
TechSupport         0
StreamingTV         0
StreamingMovies     0
Contract            0
PaperlessBilling    0
PaymentMethod       0
MonthlyCharges      0
TotalCharges        0
Churn               0
dtype: int64

In [116]:
df.nunique()

customerID          7043
gender                 2
SeniorCitizen          2
Partner                2
Dependents             2
tenure                73
PhoneService           2
MultipleLines          3
InternetService        3
OnlineSecurity         3
OnlineBackup           3
DeviceProtection       3
TechSupport            3
StreamingTV            3
StreamingMovies        3
Contract               3
PaperlessBilling       2
PaymentMethod          4
MonthlyCharges      1585
TotalCharges        6531
Churn                  2
dtype: int64

In [117]:
df.columns

Index(['customerID', 'gender', 'SeniorCitizen', 'Partner', 'Dependents',
       'tenure', 'PhoneService', 'MultipleLines', 'InternetService',
       'OnlineSecurity', 'OnlineBackup', 'DeviceProtection', 'TechSupport',
       'StreamingTV', 'StreamingMovies', 'Contract', 'PaperlessBilling',
       'PaymentMethod', 'MonthlyCharges', 'TotalCharges', 'Churn'],
      dtype='object')

In [118]:
y = df['Churn']
x = df.drop('Churn', axis=1)

In [119]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=42)

In [120]:
from sklearn.preprocessing import LabelEncoder
lb = LabelEncoder()

for col in x_train.columns:
  if(x_train[col].dtype == 'object'):
      x_train[col] = lb.fit_transform(x_train[col])
      x_test[col] = lb.fit_transform(x_test[col])

In [121]:
x_train

,customerID,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,OnlineBackup,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges
2142,2370,0,0,0,1,21,1,0,0,2,0,2,0,0,2,1,0,3,64.85,492
1623,3457,0,0,0,0,54,1,2,1,0,2,0,0,2,2,2,1,0,97.20,3511
6074,2149,1,0,1,0,1,0,1,0,0,0,0,0,0,0,0,1,2,23.45,1566
1362,1426,1,0,0,0,4,1,0,1,0,0,0,0,0,0,0,1,2,70.20,1627
6754,1545,1,0,0,1,0,1,2,0,2,2,0,2,0,0,2,1,0,61.90,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3772,375,1,0,1,0,1,1,0,1,2,0,0,0,2,2,0,1,2,95.00,5231
5191,3418,0,0,1,1,23,1,2,0,2,2,2,2,2,2,2,1,1,91.10,1466
5226,4591,1,0,1,1,12,1,0,2,1,1,1,1,1,1,0,1,2,21.15,2167
5390,4247,1,1,0,0,12,1,2,1,0,0,2,0,2,2,0,1,2,99.45,305
860,2700,1,0,0,0,26,1,0,2,1,1,1,1,1,1,1,0,1,19.80,3149

In [122]:
y_train.value_counts()

Churn
No     4138
Yes    1496
Name: count, dtype: int64

In [123]:
print(x_train.shape)
print(x_test.shape)
print(y_train.shape)
print(y_test.shape)

(5634, 20)
(1409, 20)
(5634,)
(1409,)

In [124]:
from sklearn.tree import DecisionTreeClassifier
dt = DecisionTreeClassifier(random_state=1)
dt.fit(x_train, y_train)

DecisionTreeClassifier(random_state=1)

In [125]:
from sklearn.metrics import classification_report
y_pred = dt.predict(x_test)
result = classification_report(y_test, y_pred)
print(result)

              precision    recall  f1-score   support

          No       0.81      0.72      0.76      1036
         Yes       0.41      0.54      0.46       373

    accuracy                           0.67      1409
   macro avg       0.61      0.63      0.61      1409
weighted avg       0.70      0.67      0.68      1409

In [126]:
y_pred_train = dt.predict(x_train)
result = classification_report(y_train, y_pred_train)
print(result)

              precision    recall  f1-score   support

          No       1.00      1.00      1.00      4138
         Yes       1.00      1.00      1.00      1496

    accuracy                           1.00      5634
   macro avg       1.00      1.00      1.00      5634
weighted avg       1.00      1.00      1.00      5634

In [127]:
from sklearn.ensemble import RandomForestClassifier, BaggingClassifier

In [128]:
bag_class = BaggingClassifier(
    estimator=DecisionTreeClassifier(),
    n_estimators=50,
    random_state=7,
    oob_score=True
)

In [129]:
bag_model = bag_class.fit(x_train,y_train)

In [130]:
bag_model.oob_score_

0.7804401845935393

In [ ]:
y_pred_bag_train = bag_model.predict(x_train)
result_bag_train = classification_report(y_train, y_pred_bag_train)
print(result_bag_train)

              precision    recall  f1-score   support

          No       1.00      1.00      1.00      4138
         Yes       1.00      1.00      1.00      1496

    accuracy                           1.00      5634
   macro avg       1.00      1.00      1.00      5634
weighted avg       1.00      1.00      1.00      5634

In [ ]:
y_pred_bag_test = bag_model.predict(x_test)
result_bag_test = classification_report(y_test, y_pred_bag_test)
print(result_bag_test)

In [ ]:
from sklearn.ensemble import RandomForestClassifier

In [ ]:
rf_classifier = RandomForestClassifier(
    n_estimators=25,  # Number of decision trees in the forest
    max_features=6,  # Maximum number of features considered for splitting
    criterion='gini',  # The function to measure the quality of a split (Gini impurity)
    max_depth=10,  # Maximum depth of the decision trees
    min_impurity_decrease=0.05,  # Minimum impurity decrease required for a split
    bootstrap=True,  # Whether bootstrap samples are used when building trees
    oob_score=True,  # Whether to use out-of-bag samples to estimate generalization accuracy
    class_weight='balanced',  # Weights associated with classes to handle class imbalance
    random_state=7  # Controls the random seed for reproducibility
)

In [ ]:
rf_model = rf_classifier.fit(x_train, y_train)

In [ ]:
y_pred_bag_train1 = rf_model.predict(x_train)
result_bag_train1 = classification_report(y_train, y_pred_bag_train1)
print(result_bag_train1)

In [ ]:
y_pred_bag_train1 = rf_model.predict(x_test)
result_bag_train1 = classification_report(y_test, y_pred_bag_train1)
print(result_bag_train1)

In [ ]:
from sklearn.model_selection import GridSearchCV

In [ ]:
params = {
    "n_estimators": [25, 50, 5, 100],  # Number of decision trees in the forest
    "criterion": ["entropy", "gini"],  # The function to measure the quality of a split
    "max_depth": [5, 10, 12, 15],  # Maximum depth of the decision trees
    "max_features": [5, 6, 7, 8]  # Maximum number of features considered for splitting
}

In [ ]:
grid_model = GridSearchCV(
    estimator=RandomForestClassifier(),  # The base estimator to be tuned, in this case, RandomForestClassifier
    param_grid=params,  # The parameter grid containing hyperparameter values to be searched
    scoring='f1',  # The scoring metric to optimize for during hyperparameter tuning, in this case, F1-score
    cv=10,  # Number of folds for cross-validation
    verbose=3,  # Controls the verbosity of the grid search process
    n_jobs=-1  # Number of jobs to run in parallel (-1 means using all available cores)
)

In [141]:
grid_model.fit(x_train, y_train)

Fitting 10 folds for each of 128 candidates, totalling 1280 fits

GridSearchCV(cv=10, estimator=RandomForestClassifier(), n_jobs=-1,
             param_grid={'criterion': ['entropy', 'gini'],
                         'max_depth': [5, 10, 12, 15],
                         'max_features': [5, 6, 7, 8],
                         'n_estimators': [25, 50, 5, 100]},
             scoring='f1', verbose=3)

In [142]:
# Access the best estimator found by GridSearchCV
best_rf_estimator = grid_model.best_estimator_
best_rf_estimator

RandomForestClassifier(criterion='entropy', max_depth=5, max_features=5,
                       n_estimators=25)

In [143]:
print("Best Estimator: \n{}\n".format(grid_model.best_estimator_))

# Print the best parameters found by GridSearchCV
print("Best Parameter: \n{}\n".format(grid_model.best_params_))

Best Estimator:
RandomForestClassifier(criterion='entropy', max_depth=5, max_features=5,
                       n_estimators=25)

Best Parameter:
{'criterion': 'entropy', 'max_depth': 5, 'max_features': 5, 'n_estimators': 25}

In [144]:
random_classifier = RandomForestClassifier(
    n_estimators= 25,
    max_depth = 5,
    max_features=5,
    criterion='entropy',
    random_state=7,
    oob_score=True,
    bootstrap=True
)

In [145]:
rd = random_classifier.fit(x_train, y_train)

In [146]:
rd_train = rd.predict(x_train)
result_rd_train = classification_report(y_train, rd_train)
print(result_rd_train)

              precision    recall  f1-score   support

          No       0.81      0.94      0.87      4138
         Yes       0.71      0.41      0.52      1496

    accuracy                           0.80      5634
   macro avg       0.76      0.67      0.70      5634
weighted avg       0.79      0.80      0.78      5634

In [109]:
rd_test = rd.predict(x_test)
result_rd_test = classification_report(y_test, rd_test)
print(result_rd_test)

              precision    recall  f1-score   support

          No       0.81      0.94      0.87      1036
         Yes       0.72      0.40      0.52       373

    accuracy                           0.80      1409
   macro avg       0.77      0.67      0.70      1409
weighted avg       0.79      0.80      0.78      1409

In [147]:
from sklearn.model_selection import RandomizedSearchCV

In [148]:
# Create a RandomizedSearchCV instance
random_model = RandomizedSearchCV(
    estimator=RandomForestClassifier(),  # The base estimator to be tuned, in this case, RandomForestClassifier
    scoring='f1',  # The scoring metric to optimize for during hyperparameter tuning, in this case, F1-score
    param_distributions=params,  # The parameter distributions for sampling hyperparameters
    cv=5,  # Number of folds for cross-validation
    verbose=1,  # Controls the verbosity of the search process
    n_jobs=-1  # Number of jobs to run in parallel (-1 means using all available cores)
)

In [149]:
random_model.fit(x_train, y_train)

Fitting 5 folds for each of 10 candidates, totalling 50 fits

RandomizedSearchCV(cv=5, estimator=RandomForestClassifier(), n_jobs=-1,
                   param_distributions={'criterion': ['entropy', 'gini'],
                                        'max_depth': [5, 10, 12, 15],
                                        'max_features': [5, 6, 7, 8],
                                        'n_estimators': [25, 50, 5, 100]},
                   scoring='f1', verbose=1)

In [150]:
RandomizedSearchCV(
    cv=5,  # Number of folds for cross-validation
    estimator=RandomForestClassifier(),  # The base estimator to be tuned, in this case, RandomForestClassifier
    n_jobs=-1,  # Number of jobs to run in parallel (-1 means using all available cores)
    param_distributions={  # The parameter distributions for sampling hyperparameters
        'criterion': ['entropy', 'gini'],  # The function to measure the quality of a split
        'max_depth': [5, 10, 12, 15],  # Maximum depth of the decision trees
        'max_features': [5, 6, 7, 8],  # Maximum number of features considered for splitting
        'n_estimators': [25, 50, 75, 100]  # Number of decision trees in the forest
    },
    scoring='f1',  # The scoring metric to optimize for during hyperparameter tuning
    verbose=3  # Controls the verbosity of the search process
)

RandomizedSearchCV(cv=5, estimator=RandomForestClassifier(), n_jobs=-1,
                   param_distributions={'criterion': ['entropy', 'gini'],
                                        'max_depth': [5, 10, 12, 15],
                                        'max_features': [5, 6, 7, 8],
                                        'n_estimators': [25, 50, 75, 100]},
                   scoring='f1', verbose=3)

In [151]:
random_model.best_estimator_

RandomForestClassifier(criterion='entropy', max_depth=15, max_features=8,
                       n_estimators=5)